version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: ${PRISMA_SECRET}
        databases:
          default:
            connector: postgres
            host: ec2-54-83-33-14.compute-1.amazonaws.com
            database: dde6cj4l2rof4o
            schema: public
            user: xijfwigjqhntyq
            password: e2c64c26267643ce9a5bf4314affca44ff151dedbd77e8addcafa328d7f33ca4
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true